[package]
name = "mock_ft"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.15.1"
near-contract-standards = "5.15.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"